/**
 * POST /api/chat  { message, page?, history? }
 * The per-message endpoint the on-site chat widget calls.
 *
 * Retrieval is always grounded in this site's own content (built by knowledge.ts).
 * If OPENAI_API_KEY is set, the reply text is generated by OpenAI from that
 * retrieved context (hybrid RAG); otherwise — or if the API call fails — it
 * falls back to the built-in deterministic templates. Same-origin, Node runtime.
 */
import { answer } from "@/lib/chatbot/agent";
import { isOpenAIEnabled, llmAnswer } from "@/lib/chatbot/openai";
import type { ChatRequest, ChatTurn } from "@/lib/chatbot/types";
import { getChatIndex } from "@/lib/chatbot/knowledge";
import { getSiteConfig } from "@/lib/data";

export const runtime = "nodejs";

export async function POST(req: Request) {
  let body: any;
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const message = typeof body?.message === "string" ? body.message.slice(0, 1000) : "";

  const site = await getSiteConfig();
  const index = getChatIndex(site);

  const request: ChatRequest = {
    siteId: index.siteId,
    message,
    page: sanitizePage(body?.page),
    history: sanitizeHistory(body?.history),
  };

  // Empty message = the widget's initial greeting request. Always answer that
  // deterministically (config greeting) — no need to spend a model call.
  if (message && isOpenAIEnabled()) {
    try {
      return Response.json(await llmAnswer(index, request));
    } catch (err) {
      // Degrade gracefully to the no-LLM brain instead of erroring the widget.
      console.error("[chat] OpenAI generation failed, falling back:", err);
    }
  }

  return Response.json(answer(index, request));
}

/** Trust nothing from the widget's page payload; cap sizes. */
function sanitizePage(page: any): ChatRequest["page"] {
  if (!page || typeof page !== "object") return undefined;
  const str = (v: unknown, max: number) =>
    typeof v === "string" ? v.slice(0, max) : undefined;
  return {
    url: str(page.url, 2048),
    title: str(page.title, 512),
    text: str(page.text, 4000),
  };
}

/** Keep only the last few well-formed turns from the client. */
function sanitizeHistory(history: any): ChatTurn[] | undefined {
  if (!Array.isArray(history)) return undefined;
  const turns: ChatTurn[] = [];
  for (const t of history.slice(-12)) {
    const role = t?.role === "bot" ? "bot" : t?.role === "user" ? "user" : null;
    const text = typeof t?.text === "string" ? t.text.slice(0, 1000) : "";
    if (role && text) turns.push({ role, text });
  }
  return turns.length ? turns : undefined;
}
